### ISSUE TITLE
Tests rely on incorrect assumptions about active bindings

### ISSUE THREAD

**Issue by wch** [HopkinsIDD/ForecastFramework#36]
I'm about to submit a new version of R6 to CRAN, but am getting errors with this package when I run checks on reverse dependencies.

Some background: In previous versions of R6, when cloning an object with active bindings, it will extract the function for the active binding _at cloning time_ and put it in the new object. This relied on behavior from `as.list.environment` which apparently was a bug, and will be changed in upcoming versions of R. The bug was that `as.list.environment` would give the function behing an active binding, rather than the value that the function returns when invoked. In upcoming versions of R, it will call the function and return that value. In the dev version of R6, it separately stores the functions for active bindings when an R6 object is created, and uses those stored functions to create new active bindings when the object is cloned.

This relates to ForecastFramework because ForecastFramework instantiates some classes with active bindings at build time. For example, in the `Forecasts` class, it instantiates `Generic` and `MatrixData` when the class is created -- not when each `Forecasts` object is instantiated:

https://github.com/HopkinsIDD/ForecastFramework/blob/881ea2d49e4764835347c570efa4bba9ce8de32e/R/Forecasts.R#L31-L32

The `MatrixData` object in turn has a number active bindings. However, when an R package is built, the active bindings are made to be no longer active. From the docs at https://stat.ethz.ch/R-manual/R-devel/library/base/html/bindenv.html : "Currently active bindings are not preserved during package installation, but they can be created in .onLoad."

Here's an example that illustrates. Compare the results of `MatrixData$new()` to `Forecast$new()$data`. Both should be MatrixData objects, but the former has active bindings while the latter does not.

```
> library(ForecastFramework)
> MatrixData$new()
<MatrixData>
  Inherits from: <DataContainer>
  Public:
    clone: function (deep = FALSE) 
    cnames: active binding
    colData: active binding
    debug: function (string) 
    initialize: function (...) 
    mat: active binding
    metaData: active binding
    ncol: active binding
    nrow: active binding
    rnames: active binding
    rowData: active binding
    undebug: function (string) 
  Private:
    .cellData: list
    .cnames: NULL
    .colData: list
    .debug: 
    .mat: 
    .metaData: list
    .ncol: 0
    .nrow: 0
    .rnames: NULL
    .rowData: list
    checkType: function (name, val, type = "self") 
    defaultAbstract: function (...) 
    defaultActive: function (name, type, value) 
> Forecast$new()$data
<MatrixData>
  Inherits from: <DataContainer>
  Public:
    clone: function (deep = FALSE) 
    cnames: NULL
    colData: list
    debug: function (string) 
    initialize: function (...) 
    mat: 
    metaData: list
    ncol: 0
    nrow: 0
    rnames: NULL
    rowData: list
    undebug: function (string) 
  Private:
    .cellData: list
    .cnames: NULL
    .colData: list
    .debug: 
    .mat: 
    .metaData: list
    .ncol: 0
    .nrow: 0
    .rnames: NULL
    .rowData: list
    checkType: function (name, val, type = "self") 
    defaultAbstract: function (...) 
    defaultActive: function (name, type, value) 
```

The latter object will probably not behave as expected when it is cloned, and (I believe) it results in test failures.

For example, in test-6-MoveAheadModel.R:

```
> test_RecursiveForecastModel(testMoveAheadModel1,"MoveAheadModel",is_same_RecursiveForecastModel_as,testData1,"Empty IncidenceMatrix",is_same_MatrixData_as)
 Error: Test failed: 'MoveAheadModel : fit works on data : Empty IncidenceMatrix'
* `firstModel` not equal to `model`.
Component “.__enclos_env__”: Component “private”: Component “.data”: Component “.__enclos_env__”: Component “super”: Component “.__enclos_env__”: Component “super”: Component “.__enclos_env__”: Component “super”: Component “metaData”: Modes of target, current: function, list
Component “.__enclos_env__”: Component “private”: Component “.data”: Component “.__enclos_env__”: Component “super”: Component “.__enclos_env__”: Component “super”: Component “.__enclos_env__”: Component “super”: Component “metaData”: target, current do not match when deparsed
Component “.__enclos_env__”: Component “private”: Component “.data”: Component “.__enclos_env__”: Component “super”: Component “.__enclos_env__”: Component “super”: Component “cnames”: Modes of target, current: func 
```

Note that this happens when you install the package and load it with `library(ForecastFramework`, but it will **not** happen when you load the package with `devtools::load_all()`. That is because `load_all()` loads the package without installing it, and without converting the active binding to a static value.

I believe that the problem is that the test is based on the assumption that the compared values are **not** active bindings; the dev version of R6 will restore active bindings when an object is cloned, even if they were converted to static values. Please fix this and make it work with the development version of R6, which you can install with:

```R
devtools::install_github('r-lib/R6@rc-v2.4.1')
```

Again, please keep in mind that these errors occur only when the package is loaded the normal way, but not when `load_all()` is used.

Since I have been asked by a member of R-core to submit this fixed version of R6, I want to release it as soon as possible, but this requires that an updated version of ForecastFramework is on CRAN first.

**Comment by wch** [comment]
Also, it's generally a good idea to instantiate reference objects in a class's initialize method, not when the class is created. See https://r6.r-lib.org/articles/Introduction.html#fields-containing-reference-objects

**Comment by jkamins7** [comment]
This should be an easy enough change.  I was mostly doing this as a way of documenting strong typing.  Let me test something and get back to this.  Hopefully this will be an easy fix.

**Comment by jkamins7** [comment]
Two questions.

I'm not sure how to run my tests so  that they show these errors.  Is there a better solution than running library and manually running the test cases?

Second, I believe that replacing:
```{r}
R6::R6Class(
  private = list(
    .field = AnotherR6Class$new()
  ),
  active = list(
    field = function(value){
      something with <private$field()>
    }
  )
)
```
with 
```{r}
fake_instance <- function(obj){
  rc <- list()
  class(rc) <- class(obj)
  return(rc)
}

R6::R6Class(
  private = list(
    .field = fake_instance(AnotherR6Class$new())
  ),
  active = list(
    field = function(value){
      something with <private$field()>
    }
  )
)```
is sufficient (and passed my initial tests).  I think this should fix the problem, but can you confirm that I understand the situation correctly?

**Comment by wch** [comment]
I was able to get the errors to happen when running `R CMD check` on the package tarball, or by using Build -> Check Package in RStudio. I also got the errors when running the manually i the console. I had other weird errors when I used `devtools::test()` and couldn't figure out why, so I gave up.


I think your change could make it work, but why have an object that pretends to be an object of a different class? You could set `.field=NULL` and then in the `initialize` method do `private$.field <- AnotherR6Class$new()`.

**Comment by wch** [comment]
Note that when I say "make it work", I just mean that it could make the tests pass. I'm not sure what exactly you're trying to achieve with the structure of these classes so I can't really say whether it's a good way to go. I will say, though, that populating it in the `initialize` method is the way one would typically do it.

**Comment by wch** [comment]
FYI, I'm planning on releasing R6 to CRAN in two days, which will cause errors for the version of ForecastFramework that's currently on CRAN.

**Comment by jkamins7** [comment]
This should now be fixed both here and on CRAN.  I was having some problems with win-builder, sorry for the delay. I hope you didn't delay the R6 upgrade for this.
